version: "3.8"

services:
  app:
    image: ghcr.io/mealie-recipes/mealie
    restart: unless-stopped
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - BASE_URL
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    volumes:
      - app_data:/app/data/
    networks:
      proxy_apps:
      default:
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_DB=mealie
    volumes:
      - db_data:/var/lib/postgresql/data
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.mealiedbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.mealiedbbackup.command: "sh -c 'pg_dumpall -U mealie -f /var/lib/postgresql/data/backup.sql'"
    networks:
      default:

volumes:
  app_data:
  db_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
